### ISSUE TITLE
emmet: extra packaging steps may be required

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/vscode-builtin-extensions#18]
Based on the upstream (theia) repo, there looks to be a problem with `emmet` and one of it's dependencies (`vscode-emmet-helper`) https://github.com/eclipse-theia/theia/issues/7019.

The builtin complains about the following when attempting to perform IntelliSense:

```
Uncaught Error: Cannot find module 'vscode-emmet-helper'

Error: Cannot find module 'vscode-emmet-helper'
    at Function.Module._resolveFilename (:3000/internal/modules/cjs/loader.js:582)
    at Function.Module._load (:3000/internal/modules/cjs/loader.js:508)
    at Function.module._load (:3000/Users/vincentfugnitto/workspace/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js:80)
    at Module.require (:3000/internal/modules/cjs/loader.js:637)
    at require (:3000/internal/modules/cjs/helpers.js:22)
    at Object.<anonymous> (:3000/Users/vincentfugnitto/workspace/theia/plugins/vscode-builtin-emmet/extension/dist/extension.js:1)
    at n (:3000/Users/vincentfugnitto/workspace/theia/plugins/vscode-builtin-emmet/extension/dist/extension.js:1)
    at Object.t.getEmmetHelper (:3000/Users/vincentfugnitto/workspace/theia/plugins/vscode-builtin-emmet/extension/dist/extension.js:1)
    at t.DefaultCompletionItemProvider.provideCompletionItemsInternal (:3000/Users/vincentfugnitto/workspace/theia/plugins/vscode-builtin-emmet/extension/dist/extension.js:1)
    at t.DefaultCompletionItemProvider.provideCompletionItems (:3000/Users/vincentfugnitto/workspace/theia/plugins/vscode-builtin-emmet/extension/dist/extension.js:1)
    at errors.ts:26
```

I'm thinking it might be a similar issue as `typescript` where we had to perform some manual steps to package correctly.

**Comment by marcdumais-work** [comment]
Good find.

Repo for the missing dependency: https://github.com/microsoft/vscode-emmet-helper

**Comment by akosyakov** [comment]
I think we used to run `npm install` for it to install missing dependencies: https://github.com/microsoft/vscode/blob/master/extensions/emmet/package.json#L451-L458

but removed it for some reasons

**Comment by marcdumais-work** [comment]
> I think we used to run `npm install` for it to install missing dependencies

Interesting, thanks Anton. I can try that to see if it works.

@vince-fugnitto Any advice on reproducing the error above? e.g. just open an `emmet` file?

**Comment by akosyakov** [comment]
Looked through the history we did for other extensions, but not for `emmet`: https://github.com/theia-ide/vscode-builtin-extensions/commit/9886f609c931ac7209cb10774a7a460ba9d42e4b#diff-f893c686152807955938cc453df4f2e0R26-R28

**Comment by vince-fugnitto** [comment]
> > I think we used to run `npm install` for it to install missing dependencies
> 
> Interesting, thanks Anton. I can try that to see if it works.
> 
> @vince-fugnitto Any advice on reproducing the error above? e.g. just open an `emmet` file?

The error is reproduced by having a `html` file (ex: index.html), and attempting to use autocompletion to select `emmet` snippets. The error is soon after thrown.

**Comment by marcdumais-work** [comment]
> Looked through the history we did for other extensions, but not for `emmet`: [9886f60#diff-f893c686152807955938cc453df4f2e0R26-R28](https://github.com/theia-ide/vscode-builtin-extensions/commit/9886f609c931ac7209cb10774a7a460ba9d42e4b#diff-f893c686152807955938cc453df4f2e0R26-R28)

That seems to help! Before doing this I could not get emmet to be active like in VS Code. Now it works.

Before:
![Peek 2020-03-18 09-57](https://user-images.githubusercontent.com/25749063/76968213-e61f1500-68fe-11ea-9142-8c05d76a2245.gif)

after:
![Peek 2020-03-18 09-46](https://user-images.githubusercontent.com/25749063/76967171-6cd2f280-68fd-11ea-9e82-d82b6027c401.gif)

@vince-fugnitto I am not sure however if this fixes the problem you report here. With our published version of emmet, I do not get this emmet pop-up but no exception either. You get the exception doing the same?

Note: testing with the electron-example app.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I am not sure however if this fixes the problem you report here. With our published version of emmet, I do not get this emmet pop-up but no exception either. You get the exception doing the same?

I'm testing on `master` and electron. When performing the keybinding <kbd>ctrl</kbd>+<kbd>space</kbd> to trigger the auto-suggestions, the error is thrown:

<div align='center'>

![emmet](https://user-images.githubusercontent.com/40359487/76969489-d0125400-6900-11ea-98bf-e5abf05826ea.gif)


</div>

**Comment by marcdumais-work** [comment]
Ah, frontend exception - I had assumed backend for some reason. Now I can reproduce, thanks!

**Comment by marcdumais-work** [comment]
> Looked through the history we did for other extensions, but not for `emmet`: [9886f60#diff-f893c686152807955938cc453df4f2e0R26-R28](https://github.com/theia-ide/vscode-builtin-extensions/commit/9886f609c931ac7209cb10774a7a460ba9d42e4b#diff-f893c686152807955938cc453df4f2e0R26-R28)

So the 2 node-debug extensions no longer seem to be present, but `debug-auto-launch` is still there. I wonder if we should still install its production dependencies? 

@vince-fugnitto would you know how to test this extension to confirm if it works ok right now?
