### ISSUE TITLE
Add info required for registry's extension page  

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/vscode-builtin-extensions#19]
Each builtin's `package.json` should be [dynamically updated]( https://github.com/theia-ide/vscode-builtin-extensions/blob/master/src/package-vsix.js#L75
) to provide basic info, to be displayed in Open VSX's extension page. 

ATM many expected fields are missing or contain bogus info, and so the extension's page is not good:

![image](https://user-images.githubusercontent.com/25749063/76899676-6ba6b480-686e-11ea-8474-daa0c7a7be44.png)

We would also need an icon for the front page. ATM nothing: 

![image](https://user-images.githubusercontent.com/25749063/76899646-592c7b00-686e-11ea-8d71-db712eb76657.png)

Example of a fully-filled `package.json`: https://github.com/microsoft/vscode-cpptools/blob/master/Extension/package.json

**Comment by akosyakov** [comment]
We should align the registry that it works with any VS Code extension. We won't be able to update properties of all extension out there. cc @spoenemann

**Comment by spoenemann** [comment]
I think we can close this in favor of https://github.com/eclipse/openvsx/issues/19

**Comment by marcdumais-work** [comment]
> We won't be able to update properties of all extension out there.

Agreed.

> We should align the registry that it works with any VS Code extension. 

The built-ins may be a little special, since they were not really meant to be published on the Marketplace. 

This is for example what we have to work-with: https://github.com/microsoft/vscode/blob/master/extensions/bat/package.json

**Comment by marcdumais-work** [comment]
> I think we can close this in favor of [eclipse/openvsx#19](https://github.com/eclipse/openvsx/issues/19)

I'm happy to let you take care of this if the end-result is the same. Will you be able to add missing icons as well?

**Comment by spoenemann** [comment]
Missing icons is tracked here: https://github.com/eclipse/openvsx/issues/38

I don't know when I'll have time to take care of all this, it's already a lot on the list. It's time for more contributors to step up for openvsx :-)
