### ISSUE TITLE
Need an icon for builtins that do not have one

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/vscode-builtin-extensions#21]
I am thinking of a generic "built-in" icon, to be used for all built-ins that do not have one by default. Something very simple, for example a box with on each side an arrow pointing to the center.

@vince-fugnitto could you propose something?

This is what it looks like on Open VSX when no icon is provided:
![image](https://user-images.githubusercontent.com/25749063/76909924-03ae9900-6883-11ea-9045-58096ce0bebc.png)

![image](https://user-images.githubusercontent.com/25749063/76909958-1923c300-6883-11ea-9162-99ae9c344655.png)

**Comment by vince-fugnitto** [comment]
@marcdumais-work looking for `@builtin` extensions in vscode I see a number of them have icons which is good. I also see that vscode gives "language" extensions the same [icon](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/extensions/browser/media/language-icon.svg):

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/76910281-fa71fc00-6883-11ea-9d20-dbdf53fbef19.png)

</div>

I can propose a simple icon for most cases (something which looks like an extension logo).

**Comment by akosyakov** [comment]
@spoenemann Can we reuse the same icon which we use in Theia as a placeholder in the registry.
I don't think we should fix it in this repo. There can be other extensions without icons, especially under development

**Comment by akosyakov** [comment]
> https://github.com/theia-ide/vscode-builtin-extensions/issues/21#issuecomment-600346062

@vince-fugnitto I think it is an enhancement request for Theia.

**Comment by spoenemann** [comment]
> Can we reuse the same icon which we use in Theia as a placeholder in the registry.
I don't think we should fix it in this repo. There can be other extensions without icons, especially under development

:+1: please create an openvsx issue.

**Comment by akosyakov** [comment]
> 👍 please create an openvsx issue.

https://github.com/eclipse/openvsx/issues/38

**Comment by marcdumais-work** [comment]
Closing in favor of eclipse/openvsx#38
