### ISSUE TITLE
Publish vscode.github-authentication builtin

### ISSUE THREAD

**Issue by jeluard** [theia-ide/vscode-builtin-extensions#29]
`vscode.github-authentication` is required by https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github.

It would be great to have it published.

**Comment by marcdumais-work** [comment]
Hi @jeluard ,

It's published now, but untested AFAIK. Maybe you can let us know how it goes: 

https://open-vsx.org/extension/vscode/github-authentication

**Comment by jeluard** [comment]
Looks like it works! Thanks
