### ISSUE TITLE
How to build with Node 10 ?

### ISSUE THREAD

**Issue by elaihau** [theia-ide/vscode-builtin-extensions#3]
Recently Jacques and I have been playing with vscode builtin extensions such as grunt, gulp, npm, and jake to achieve the compatibility.

We built extensions from source available at https://github.com/theia-ide/vscode-builtin-extensions. And this morning we noticed that, some extensions, such as gulp, did not build any more since we moved to Node 10.

As vscode uses Node 10 since Feb (i.e., https://github.com/Microsoft/vscode/pull/68098), we thought using Node 10 on the latest released version of code would work. So, we updated `vscode-builtin-extensions/vscode` to 1.33.0 as a submodule and rebuilt, but it still failed.

```
[11:54:23] Using gulpfile ~/dev/vscode-builtin-extensions/vscode/gulpfile.js
[11:54:23] Task never defined: compile-extensions-build
[11:54:23] To list available tasks, try running: gulp --tasks
error Command failed with exit code 1.
```

is there a way to get around this error? Thanks !

**Comment by akosyakov** [comment]
upgraded to vscode 1.33.0 to build with Node 10

**Comment by daisuke-yoshimoto** [comment]
@akosyakov 
Could you publish vscode-builtin-extensions built with Node 10 to npm registry?
