### ISSUE TITLE
html-language-features should be built with typescript dependency

### ISSUE THREAD

**Issue by shahar-h** [theia-ide/vscode-builtin-extensions#33]
`html-language-features` builtin vscode extension has an implicit dependency on typescript: https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/server/src/modes/javascriptMode.ts#L16
As a result it is built and published to open-vsx registry without typescript, so LS breaks in runtime unless typescript is installed globally or hoisted to root node modules from some other package. 
I guess it should be treated the same way as `typescript-language-features`: https://github.com/theia-ide/vscode-builtin-extensions/blob/2b05138480817fc99b8ca695172db3743db840d2/src/package-vsix.js#L41.

**Comment by marcdumais-work** [comment]
Thanks for submitting this issue @shahar-h . I think you're exactly right, I'll see if I can handle it like `typescript-language-features`

**Comment by marcdumais-work** [comment]
@shahar-h  I have a tentative, as of yet untested fix: #34

**Comment by marcdumais-work** [comment]
This version was published by CI after I merged the fix: it should work:

https://open-vsx.org/api/vscode/html-language-features/1.48.0-next.4a1bcdafe9/file/vscode.html-language-features-1.48.0-next.4a1bcdafe9.vsix
