### ISSUE TITLE
consider to pack as vsix and publish as GitHub releases

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/vscode-builtin-extensions#5]
There are 2 gotchas:
- VS Code team does not package these extensions, so it could be impossible because of missing attributes or files
- pulling from GitHub require GitHub token compare to npm

**Comment by marcdumais-work** [comment]
@akosyakov you mention potential downsides, but what would be the main advantage(s) to distribute these built-in extensions as vsix file(s) vs NPM packages?

**Comment by akosyakov** [comment]
There are probably could be 2:
- less magic in the plugin system, if you can just consume vsix
- the same packaging as non built-in extensions

**Comment by akosyakov** [comment]
Another reason to do it: https://github.com/eclipse-theia/theia/pull/6207

**Comment by akosyakov** [comment]
We go with publishing to Open VSX Registry instead.
